### ISSUE TITLE
[Feature Request] P2SH by type Auth

### ISSUE THREAD

**Issue by phroi** [cryptape/omnilock#4]
Hello Cryptape, iCKB here :wave:

I noticed that [Cryptape is re-developing Omnilock to be CoBuild compatible](https://github.com/cryptape/omnilock/pull/3) and eventually Cryptape will redeploy the Omnilock. At the same time, the impeding transition to CoBuild and CoBuild OTX has forced me to re-evaluate iCKB from the contracts up.

As per Nervos Talk post, [*CoBuild, Omnilock and Administrator Mode*](https://talk.nervos.org/t/cobuild-omnilock-and-administrator-mode/7918), I'm evaluating a design based on [Omnilock's Administrator Mode](https://blog.cryptape.com/omnilock-a-universal-lock-that-powers-interoperability-1#heading-administrator-mode) for the limit order contract. Briefly, a Limit Order design could use Omnilock as base and be unlocked either:
- By user with signature, as usual.
- Using Administrator Mode with Limit Order Domain Logic included as P2SH.

In this design there are two kind of cells:

```
Limit Order cell:
- Lock: Omnilock with Domain Logic P2SH Auth Administrator Mode 
- Type: sUDT
- Data: [amount, ... limit order data]

Domain Logic cell:
- Lock: Domain Logic to validate limit orders
- Type: ...
```

Considerations:
- Including Domain Logic as Lock Script is inconvenient, but P2SH auth rules require to use lock script for validation. It would be so much more convenient to include it as Type Script, as the evolution form sUDT to xUDT showed.
- From an OTX CoBuild perspective, the Limit Order cell would be an Action without any matching type script. Then again CoBuild validation rules require all Action objects to have a matching type script in the fully assembled CKB Transaction.
- Limit Orders are just an example from a much broader class of DApps. If Omnilock implements P2SH by type Auth, then a new class of DApps becomes much easier to develop, even in a Cobuild OTX environment. The following cell becomes the only cell needed by both P2SH by type Auth and CoBuild OTX:

```
Domain Logic cell:
- Lock: ...
- Type: Domain Logic to validate limit orders
```

**Could Cryptape implement P2SH by type Auth in Omnilock as a new [Auth flag](https://blog.cryptape.com/omnilock-a-universal-lock-that-powers-interoperability-1#heading-authentication)?**

**Comment by XuJiandong** [comment]
Could you write some pseudo code about this feature? 

And a question to the design of second cell: Why is the logic in lock but not in type? 
```text
Domain Logic cell:
- Lock: Domain Logic to validate limit orders
- Type: ...
```

**Comment by phroi** [comment]
Hey @XuJiandong, thank you for your time and interest :hugs:

> Why is the logic in lock but not in type?

Exactly, that's the issue here! [To be P2SH compatible](https://blog.cryptape.com/omnilock-a-universal-lock-that-powers-interoperability-1#heading-authentication):
> When the auth flag is 0xFC, we will check against the current transaction, and there must be an input cell, whose lock script matches the auth content when hashed via blake160.

Without any modification to Omnilock, Domain Logic script would need to be present in the transaction possibly both as lock script (to satisfy P2SH requirements) and type script (to satisfy CoBuild action requirements).

While with the implementation of this feature, Domain Logic script would need to be present in the transaction only by type as this would satisfy requirements of both P2SH by type and CoBuild action.

> Could you write some pseudo code about this feature?

Sure, the requested feature itself is a variation of [Unlock via owner's lock script hash](https://blog.cryptape.com/omnilock-a-universal-lock-that-powers-interoperability-1#heading-unlock-via-owners-lock-script-hash). Let's say `0xFB` is the flag of P2SH by type, there are two scenarios:

**a.** Unlock via owner's type script hash in input cell:

```
CellDeps:
    <vec> Omnilock Script Cell
Inputs:
    <vec> Cell
        Data: <...>
        Type: <...>
        Lock:
            code_hash: Omnilock
            args: <flag: 0xFC> <lock hash: 0x1234> <Omnilock flags: 0>
    <vec> Cell
        Data: <...>
        Type: blake160 for this lock script must be 0x1234 <--- ONLY DIFFERENCE: FROM LOCK TO TYPE
        Lock: <...>
    <...>
Outputs:
    <vec> Any cell
Witnesses:
    WitnessArgs structure:
      Lock:
        signature: <MISSING>
        omni_identity: <MISSING>
        preimage: <MISSING>
      <...>
```

**b.** Unlock via owner's type script hash in output cell:

```
CellDeps:
    <vec> Omnilock Script Cell
    <vec> RC AdminList Cell 1
Inputs:
    <vec> Cell
        Data: <...>
        Type: <...>
        Lock:
            code_hash: Omnilock
            args: <flag: 0xFC> <lock hash: 0x1234> <Omnilock flags: 0>
    <...>
Outputs:
    <vec> Cell
        Data: <...>
        Type: blake160 for this lock script must be 0x1234
        Lock: <...>
    <...>
Witnesses:
    WitnessArgs structure:
      Lock:
        signature: <MISSING>
        omni_identity: <MISSING>
        preimage: <MISSING>
      <...>
```

The use in conjunction with administrator mode is a variation of [Unlock via administrator's lock script hash (1)](https://blog.cryptape.com/omnilock-a-universal-lock-that-powers-interoperability-1#heading-unlock-via-administrators-lock-script-hash-1). Let's say `0xFB` is the flag of P2SH by type, there are two scenarios:

**a.** Unlock via administrator's type script hash in input cell:

```
CellDeps:
    <vec> Omnilock Script Cell
    <vec> RC AdminList Cell 1
Inputs:
    <vec> Cell
        Data: <...>
        Type: <...>
        Lock:
            code_hash: Omnilock
            args: <flag: 0> <pubkey hash 1> <Omnilock flags: 1> <RC AdminList Cell 1's type ID>
    <vec> Cell
        Data: <...>
        Type: blake160 for this lock script must be 0x1234 <--- ONLY DIFFERENCE: FROM LOCK TO TYPE
        Lock: <...>
    <...>
Outputs:
    <vec> Any cell
Witnesses:
    WitnessArgs structure:
      Lock:
        signature: <MISSING>
        omni_identity:
           identity: <flag: 0xFB> <lock hash: 0x1234>
           proofs: <SMT proofs for the above identity in RC AdminList Cell 1>
        preimage: <MISSING>
      <...>
```

**b.** Unlock via administrator's type script hash in output cell:

```
CellDeps:
    <vec> Omnilock Script Cell
    <vec> RC AdminList Cell 1
Inputs:
    <vec> Cell
        Data: <...>
        Type: <...>
        Lock:
            code_hash: Omnilock
            args: <flag: 0> <pubkey hash 1> <Omnilock flags: 1> <RC AdminList Cell 1's type ID>
    <...>
Outputs:
        <vec> Cell
        Data: <...>
        Type: blake160 for this lock script must be 0x1234
        Lock: <...>
    <...>
Witnesses:
    WitnessArgs structure:
      Lock:
        signature: <MISSING>
        omni_identity:
           identity: <flag: 0xFB> <lock hash: 0x1234>
           proofs: <SMT proofs for the above identity in RC AdminList Cell 1>
        preimage: <MISSING>
      <...>
```
